---
title: "Analysis"
author: "Alayna Binder, Isabella Shubert, Preeti Nagalamadaka and Olivia Xiao"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidymodels)
library(parsnip)
library(patchwork)
library(plotly)
library(widgetframe)
library(naniar)
library(mice)
library(car)
library(MASS) # backward selection
library(bestglm)
library(glmnet) # LASSO
data <- read.csv('MICD.csv')
```

```{r imputing_data, echo=FALSE, warning=FALSE}

superdata <- data

superdata <- superdata %>%
  mutate(AGE_GROUP = case_when(AGE >= 25 & AGE <= 34 ~ '25-34', AGE >= 35 & AGE <= 44 ~ '35-44', AGE >= 45 & AGE <= 54 ~ '45-54', AGE >= 55  & AGE <= 64 ~ '55-64', AGE >= 65 & AGE <= 74 ~ '65-74', AGE >= 75 & AGE <= 84 ~ '75-84', AGE >= 85 ~ '85+')) %>%
  mutate(SEX = case_when(SEX == 0 ~ 'Female', SEX == 1 ~ 'Male')) %>%
  relocate(AGE_GROUP, .after = AGE) %>%
  dplyr::select(- c(IBS_NASL, KFK_BLOOD, S_AD_KBRIG, D_AD_KBRIG, NOT_NA_KB, LID_KB, NA_KB, FIBR_PREDS, PREDS_TAH, JELUD_TAH, FIBR_JELUD, A_V_BLOK, OTEK_LANC, RAZRIV, DRESSLER, ZSN, P_IM_STEN, LET_IS))

ect_data <- data[, c('NOT_NA_KB', 'LID_KB', 'NA_KB', 'S_AD_KBRIG', 'D_AD_KBRIG', 'REC_IM')]
ect_data_filtered <- ect_data[complete.cases(ect_data), ]
#539 patients in filtered

# # Factoring ordinal variables
# superdata$FK_STENOK = as.factor(superdata$FK_STENOK)
# superdata$IBS_POST = as.factor(superdata$IBS_POST)
# superdata$GB = as.factor(superdata$GB)
# superdata$DLIT_AG = as.factor(superdata$DLIT_AG)
# superdata$ZSN_A = as.factor(superdata$ZSN_A)
# superdata$TIME_B_S = as.factor(superdata$TIME_B_S)
# 
# # Superdata for admission
# superdata_admission <- superdata %>%
#   dplyr::select(- c(R_AB_1_n, NA_R_1_n, NOT_NA_1_n, R_AB_2_n, NA_R_2_n, NOT_NA_2_n, R_AB_3_n, NA_R_3_n, NOT_NA_3_n))
# 
# # Superdata for stay
# superdata_stay <- superdata %>%
#   dplyr::select(c(R_AB_1_n, NA_R_1_n, NOT_NA_1_n, R_AB_2_n, NA_R_2_n, NOT_NA_2_n, R_AB_3_n, NA_R_3_n, NOT_NA_3_n))
# 
# # Imputing data to get rid of missing data
# imputation_model <- mice(superdata, m = 1, method = "pmm")
# imputed_data <- complete(imputation_model, action = "long", include = FALSE)

#imputing ect data
imputation_model_ect <- mice(ect_data_filtered, m = 1, method = "pmm")
imputed_data_ect <- complete(imputation_model_ect, action = "long", include = FALSE)
# 
# # Imputed data for admission
# imputed_data_admission <- imputed_data %>%
#   dplyr::select(-c(.imp, .id, ID, AGE_GROUP, R_AB_1_n, NA_R_1_n, NOT_NA_1_n, R_AB_2_n, NA_R_2_n, NOT_NA_2_n, R_AB_3_n, NA_R_3_n, NOT_NA_3_n))
# 
# # Imputed data for stay
# imputed_data_stay <- imputed_data %>%
#   dplyr::select(c(R_AB_1_n, NA_R_1_n, NOT_NA_1_n, R_AB_2_n, NA_R_2_n, NOT_NA_2_n, R_AB_3_n, NA_R_3_n, NOT_NA_3_n, REC_IM))
# 
# # Imputed data for anamnesis (patient-given history) and ECT
# imputed_data_anamnesis <- imputed_data %>%
#   dplyr::select(c(AGE, SEX, INF_ANAM, STENOK_AN,FK_STENOK,IBS_POST,GB,SIM_GIPERT,DLIT_AG,ZSN_A,nr_11,nr_01,nr_02,nr_03,nr_04,nr_07,nr_08,np_01,np_04,np_05,np_07,np_08,np_09,np_10,endocr_01,endocr_02,endocr_03,zab_leg_01,zab_leg_02,zab_leg_03,zab_leg_06, REC_IM))
# 
# #Imputed data Admission to Hospital
# imputed_data_hospital_admit <- imputed_data %>%
#   dplyr::select(c(ritm_ecg_p_01,ritm_ecg_p_02,ritm_ecg_p_04,ritm_ecg_p_06,ritm_ecg_p_07,ritm_ecg_p_08,n_r_ecg_p_01,n_r_ecg_p_02,n_r_ecg_p_03,n_r_ecg_p_04,n_r_ecg_p_05,n_r_ecg_p_06,n_r_ecg_p_08,n_r_ecg_p_09,n_r_ecg_p_10,n_p_ecg_p_01,n_p_ecg_p_03,n_p_ecg_p_04,n_p_ecg_p_05,n_p_ecg_p_06,n_p_ecg_p_07,n_p_ecg_p_08,n_p_ecg_p_09,n_p_ecg_p_10,n_p_ecg_p_11,n_p_ecg_p_12,fibr_ter_01,fibr_ter_02,fibr_ter_03,fibr_ter_05,fibr_ter_06,fibr_ter_07,fibr_ter_08,GIPO_K,K_BLOOD,GIPER_NA,NA_BLOOD,ALT_BLOOD,AST_BLOOD,L_BLOOD,ROE,TIME_B_S, REC_IM))
# # 
# imputed_data <- read.csv('imputed_full.csv')
# # #Imputed data from time in ICU
#  imputed_data_ICU_all <- imputed_data %>%
#    dplyr::select(c(S_AD_ORIT, D_AD_ORIT,O_L_POST,K_SH_POST,MP_TP_POST,SVT_POST,GT_POST,FIB_G_POST,ant_im,lat_im,inf_im,post_im,IM_PG_P,NITR_S,LID_S_n,B_BLOK_S_n,ANT_CA_S_n,GEPAR_S_n,ASP_S_n,TIKL_S_n,TRENT_S_n,R_AB_1_n,R_AB_2_n,R_AB_3_n,NA_R_1_n,NA_R_2_n,NA_R_3_n,NOT_NA_1_n,NOT_NA_2_n,NOT_NA_3_n, REC_IM))
# 
```

```{r missing_analysis, echo=FALSE, warning=FALSE}

# Figures out which factors are most missing using naniar package
miss_var_summary(data)
# miss_var_summary(imputed_data)

#Compares missing rows
rows_with_missing_all<-  is.na(data$NOT_NA_KB) & is.na(data$NA_KB) & is.na(data$LID_KB) & is.na(data$S_AD_KBRIG) & is.na(data$D_AD_KBRIG)
print(data[rows_with_missing_all, ])

rows_with_missing_pressure <- is.na(data$S_AD_KBRIG) & is.na(data$D_AD_KBRIG)
print(data[rows_with_missing_pressure, ])

rows_with_missing_drugs <- is.na(data$NOT_NA_KB) & is.na(data$NA_KB) & is.na(data$LID_KB)
print(data[rows_with_missing_drugs, ])
```

```{r multicollinearity, echo=FALSE, warning=FALSE}

# write.csv(imputed_data_admission, "./imputed_admission.csv", row.names=FALSE)
# write.csv(imputed_data_stay, "./imputed_stay.csv", row.names=FALSE)
# write.csv(imputed_data_anamnesis, "./imputed_amanesis.csv", row.names=FALSE)
# write.csv(imputed_data_hospital_admit, "./imputed_hospital_admit.csv", row.names=FALSE)
#write.csv(imputed_data_ICU_all, "./imputed_ICU_all.csv", row.names=FALSE)
# write.csv(imputed_data, "./imputed_full.csv", row.names=FALSE)

# Using data from csv to avoid rerunning imputation
imputed_data_admission <- read.csv('imputed_admission.csv')
imputed_data_stay <- read.csv('imputed_stay.csv')
imputed_data_anamnesis <- read.csv('imputed_anamnesis.csv')
imputed_data_hospital_admit <- read.csv('imputed_hospital_admit.csv')
imputed_data_ICU_all <- read.csv('imputed_ICU_all.csv')
imputed_data <- read.csv('imputed_full.csv')
imputed_data_ect <- read.csv('imputed_ect.csv')

# Changing character sex back into numerical sex
change_sex <- function(data){
  data <- data %>% mutate(SEX = case_when(SEX == 'Female' ~ 0, SEX == 'Male' ~ 1))
}

imputed_data_admission <- change_sex(imputed_data_admission)
imputed_data_anamnesis <- change_sex(imputed_data_anamnesis)
imputed_data <- change_sex(imputed_data)

# ----------------------------------------------------------------------------
# IMPUTED_DATA

# Removing ritm_ecg_p_01 eliminated MC

imputed_data <- imputed_data %>%
  dplyr::select(-c('.imp', '.id', 'ritm_ecg_p_01', 'ID', 'AGE_GROUP'))

fit_imputed_data <- glm(REC_IM ~ ., data = imputed_data, family = 'binomial')
t(t(vif(fit_imputed_data)))
summary(fit_imputed_data)

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ADMISSION

# Removing ritm_ecg_p_01 eliminated MC
imputed_data_admission = imputed_data_admission %>%
  dplyr::select(-c(ritm_ecg_p_01))

fit_admission_log <-
  glm(REC_IM ~ ., data = imputed_data_admission, family = 'binomial')
t(t(vif(fit_admission_log)))
summary(fit_admission_log)

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ICU_ALL

fit_icu_all <- glm(REC_IM ~ ., data = imputed_data_ICU_all, family = 'binomial')
t(t(vif(fit_icu_all)))
summary(fit_icu_all)

# ----------------------------------------------------------------------------
# IMPUTED_DATA_STAY

fit_stay_log <-
  glm(REC_IM ~ ., data = imputed_data_stay, family = 'binomial')
t(t(vif(fit_stay_log)))
summary(fit_stay_log)

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ECT

imputed_data_ect <- imputed_data_ect %>%
  dplyr::select(-c('.imp', '.id'))

fit_ect <- glm(REC_IM ~ ., data = imputed_data_ect, family = 'binomial')
t(t(vif(fit_ect)))
summary(fit_ect)

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ANAMNESIS

# Removing SIM_GIPERT gets rid of MC
# imputed_data_anamnesis = imputed_data_anamnesis %>% dplyr::select(-c(SIM_GIPERT))

fit_anamnesis <- glm(REC_IM ~ ., data=imputed_data_anamnesis, family='binomial')
t(t(vif(fit_anamnesis)))

# ----------------------------------------------------------------------------
# IMPUTED_DATA_HOSPITAL_ADMIT

# Removing ritm_ecg_p_01 gets rid of MC
imputed_data_hospital_admit = imputed_data_hospital_admit %>%
  dplyr::select(-c(ritm_ecg_p_01))

fit_hosp_admit <- glm(REC_IM ~ ., data=imputed_data_hospital_admit, family='binomial')
t(t(vif(fit_hosp_admit)))

# ----------------------------------------------------------------------------
# IMPTED_DATA_ICU_ADMIT

fit_ICU_admit <- glm(REC_IM ~ ., data=imputed_data_ICU_admit, family='binomial')
t(t(vif(fit_ICU_admit)))

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ICU_STAY

fit_ICU_stay <- glm(REC_IM ~ ., data=imputed_data_ICU_stay, family='binomial')
t(t(vif(fit_ICU_stay)))

```

```{r descriptive_graphs_olivia, echo=FALSE, warning=FALSE}

#To get a stack
imputed_data_stay$REC_IM <- as.factor(imputed_data_stay$REC_IM)
 plot_day_1 <- ggplot(data = imputed_data_stay, aes(x= R_AB_1_n, fill = REC_IM))
 plot_day_1 <- plot_day_1 + geom_bar(stat="count")
 plot_day_1
 
 plot_day_2 <- ggplot(data = imputed_data_stay, aes(x= R_AB_2_n, fill = REC_IM))
 plot_day_2 <- plot_day_2 + geom_bar(stat="count")
 plot_day_2
 
 
 plot_day_3 <- ggplot(data = imputed_data_stay, aes(x= R_AB_3_n, fill = REC_IM))
 plot_day_3 <- plot_day_3 + geom_bar(stat="count")
 plot_day_3

```

```{r descriptive_graphs_preeti, echo=FALSE, warning=FALSE}

#scatter plot of age vs mi relapse
plot(imputed_data_admission$AGE,imputed_data_admission$REC_IM, main="Scatter Plot: Age", xlab="Age", ylab="MI Relapse")

#bar graph of age vs MI relapse
# Create age buckets
age_buckets <- cut(imputed_data_admission$AGE, breaks = c(0, 30, 40, 50, 60, 70, Inf), labels = c("0-30", "31-40", "41-50", "51-60", "61-70", "71+"))

# Calculate the number of people with and without the disease in each age bucket
disease_counts <- table(age_buckets, imputed_data_admission$REC_IM)

# Plot the bar graph
barplot(t(disease_counts), beside = TRUE, main = "Bar Graph: Age vs MI Relapse",
        xlab = "Age Group", ylab = "Number of People",
        legend = c("No Relapse", "Relapse"), col = c("blue", "red"))

#scatterplot of quantity of infarctions during anamnesis vs mi relapse
plot(imputed_data_admission$INF_ANAM,imputed_data_admission$REC_IM, main="Scatter Plot: Quantity of Myocardial Infarctions in Anamnesis", xlab="Number of Myocardial Infarcations in Anamnesis", ylab="MI Relapse")

```

```{r visualizations, echo=FALSE, warning=FALSE}

# Distribution of ages
# barplot(table(data$AGE), col = rainbow(300), main="Distribution of Ages in the Study",
#         xlab="Number of People",
#         ylab="Age")

# Bar Plot for Age Group by Gender
superdata %>%
  drop_na(AGE_GROUP) %>% # Remove NAs
  ggplot(aes(x = AGE_GROUP,
             fill = SEX)) +
  geom_bar() +
  labs(x = 'Age Group',
       y = 'Count',
       fill = 'Gender',
       title = 'Age Group by Gender')

```

```{r forward selection, echo = FALSE, warning = FALSE}
# FORWARD SELECTION (admission)
# - Define starting model
start.mod <- glm(REC_IM ~ 1 , data = imputed_data_admission, family = 'binomial')

# - Define stopping model 
stop.mod <- formula(glm(REC_IM ~ ., data = imputed_data_admission, 
                           family = 'binomial'))

# - Forward selection
alpha.crit <- 0.2
ffit.admission <- stats::step(start.mod,
             scope=stop.mod,
             direction="forward",
             test="F",
             trace = 0,
             k=qchisq(1-alpha.crit,1))

summary(ffit.admission)
# STENOK_AN + K_SH_POST + np_01 + n_r_ecg_p_06 + AGE +
# D_AD_ORIT + zab_leg_01 + lat_im + n_r_ecg_p_09 + NITR_S +
# GIPER_NA + n_p_ecg_p_03 + np_10 + GEPAR_S_n + TRENT_S_n +
# ANT_CA_S_n + endocr_01 + n_p_ecg_p_10 + zab_leg_02 + FIB_G_POST +
# n_p_ecg_p_11 + IBS_POST + L_BLOOD + TIME_B_S + TIKL_S_n +
# inf_im + nr_03 + ZSN_A 9 + nr_04 + ritm_ecg_p_02 +
# n_p_ecg_p_04

# 31 variables, AIC = 959.23

# ------------------------------------------------------------------------------------

# FORWARD SELECTION (stay)
# - Define starting model
start.mod2 <- glm(REC_IM ~ 1 , data = imputed_data_stay, family = 'binomial')

# Define stopping model
stop.mod2 <- formula(glm(REC_IM ~ ., data = imputed_data_stay, 
                           family = 'binomial'))

# - Forward Selection
alpha.crit <- 0.2
ffit.stay <- stats::step(start.mod2,
             scope=stop.mod2,
             direction="forward",
             test="F",
             k=qchisq(1-alpha.crit,1))
summary(ffit.stay)
# R_AB_3_n + NA_R_2_n + NA_R_1_n
# 3 variables, AIC = 1028.2
```


```{r forward selection split data, echo = FALSE, warning = FALSE}
# FORWARD SELECTION (anamnesis)
start.anamnesis <- glm(REC_IM ~ 1 , data = imputed_data_anamnesis, family = 'binomial')

stop.anamnesis <- formula(glm(REC_IM ~ ., data = imputed_data_anamnesis, 
                           family = 'binomial'))

alpha.crit <- 0.2
ffit.anamnesis <- stats::step(start.anamnesis,
             scope=stop.anamnesis,
             direction="forward",
             trace=0,
             test="F",
             k=qchisq(1-alpha.crit,1))

summary(ffit.anamnesis)
# STENOK_AN + np_01 + AGE + zab_leg_01 + zab_leg_02 + 
# IBS_POST + nr_03 +  nr_11 + endocr_01 + np_08
# 10 variables, AIC = 1008.1

# ------------------------------------------------------------------------------------

# FORWARD SELECTION (ICU all)
start.ICUall <- glm(REC_IM ~ 1 , data = imputed_data_ICU_all, family = 'binomial')

stop.ICUall <- formula(glm(REC_IM ~ ., data = imputed_data_ICU_all, 
                           family = 'binomial'))

alpha.crit <- 0.2
ffit.ICUall <- stats::step(start.ICUall,
             scope=stop.ICUall,
             direction="forward",
             trace=0,
             test="F",
             k=qchisq(1-alpha.crit,1))

summary(ffit.ICUall)
#  R_AB_3_n + NA_R_2_n + GT_POST + GEPAR_S_n + ANT_CA_S_n + TRENT_S_n + D_AD_ORIT + inf_im + NA_R_1_n
# 5 variables: AIC = 1004.3

# ------------------------------------------------------------------------------------

# FORWARD SELECTION (Hospital admit)
start.HospitalAdmit <- glm(REC_IM ~ 1 , data = imputed_data_hospital_admit, family = 'binomial')

stop.HospitalAdmit<- formula(glm(REC_IM ~ ., data = imputed_data_hospital_admit, 
                           family = 'binomial'))

alpha.crit <- 0.2
ffit.HospitalAdmit <- stats::step(start.HospitalAdmit,
             scope=stop.HospitalAdmit,
             direction="forward",
             trace=0,
             test="F",
             k=qchisq(1-alpha.crit,1))

summary(ffit.HospitalAdmit)
# ritm_ecg_p_07 + n_r_ecg_p_09 + n_r_ecg_p_06 + L_BLOOD + TIME_B_S +
# n_p_ecg_p_11 + n_r_ecg_p_03 + n_r_ecg_p_04 + n_p_ecg_p_08 + n_p_ecg_p_09 + 
# n_p_ecg_p_03
# 11 variables, AIC = 1037.3

# FORWARD SELECTION (ECT)
start.ECT <- glm(REC_IM ~ 1 , data = imputed_data_ect, family = 'binomial')

stop.ECT<- formula(glm(REC_IM ~ ., data = imputed_data_ect, 
                           family = 'binomial'))

alpha.crit <- 0.2
ffit.ECT <- stats::step(start.ECT,
             scope=stop.ECT,
             direction="forward",
             trace=0,
             test="F",
             k=qchisq(1-alpha.crit,1))

summary(ffit.ECT)
# .id + D_AD_KBRIG + NOT_NA_KB
# AIC = 274.89
```

```{r, backward-selection warning=FALSE}
# backwards selection admission - code didn't stop running

# --------------------------------------------------

# backwards selection stay
model.stay <- glm(REC_IM ~., data=imputed_data_stay,family='binomial')

bfit.stay <- model.stay %>% stepAIC(direction='backward',trace=FALSE)
summary(bfit.stay)
# NA_R_1_n + NA_R_2_n + R_AB_3_n
# AIC: 1028.2

# --------------------------------------------------

# backwards selection anamnesis
model.anamnesis <- glm(REC_IM ~., data=imputed_data_anamnesis,family='binomial')

bfit.anamnesis <- model.anamnesis %>% stepAIC(direction='backward',trace=FALSE)
summary(bfit.anamnesis)
# AGE, STENOK_AN, IBS_POST, nr_03, np_01, endocr_01, zab_leg_01, zab_leg_02
# AIC 1005.3

# --------------------------------------------------

# backwards selection ICU all
model.ICUall <- glm(REC_IM ~.,data=imputed_data_ICU_all,family='binomial')

bfit.ICUall <- model.ICUall %>% stepAIC(direction='backward',trace=FALSE)
summary(bfit.ICUall)
# D_AD_ORIT, GT_POST , inf_im , ANT_CA_S_n , GEPAR_S_n + TRENT_S_n + R_AB_3_n , NA_R_1_n + NA_R_2_n
# AIC: 1048.8

# --------------------------------------------------

# backwards selection hospital admit
model.HospitalAdmit <- glm(REC_IM ~.,data=imputed_data_hospital_admit,family='binomial')

bfit.HospitalAdmit <- model.HospitalAdmit %>% stepAIC(direction='backward',trace=FALSE)
summary(bfit.HospitalAdmit)
#  model variables: TIME_B_S2 through TIME_B_S9, L_BLOOD, ritm_ecg_p_07, n_p_ecg_p_08, n_p_ecg_p_09, n_r_ecg_03, n_r_ecg_04, n_r_ecg_p_06
# AIC:1040.8 - same AIC as forward
# --------------------------------------------------

# backwards selection ECT
model.ECT <- glm(REC_IM ~.,data=imputed_data_ect,family='binomial')

bfit.ECT <- model.ECT %>% stepAIC(direction='backward',trace=FALSE)
summary(bfit.ECT)
#  model variables: NONE

```

```{r lasso_penalized_regression, echo=FALSE, warning=FALSE}

# IMPUTED_DATA

# - Create data objects for lmnet() and cv.glment() functions:
# data objects with covariates (xx) and outcome (yy) need to be separate;
# outcome saved in a vector object;
# covariates saved in a matrix object (not a data frame!) and only include
# covariates to be considered in selection
yy <- imputed_data[,'REC_IM']
xx <- as.matrix(imputed_data[,c("AGE", "SEX", "INF_ANAM", "STENOK_AN", "FK_STENOK", "IBS_POST", "GB", "SIM_GIPERT", "DLIT_AG", "ZSN_A", "nr_11", 
"nr_01", "nr_02", "nr_03", "nr_04", "nr_07", "nr_08", "np_01", 
"np_04", "np_05", "np_07", "np_08", "np_09", "np_10", "endocr_01", 
"endocr_02", "endocr_03", "zab_leg_01", "zab_leg_02", "zab_leg_03", 
"zab_leg_04", "zab_leg_06", "S_AD_ORIT", "D_AD_ORIT", "O_L_POST", 
"K_SH_POST", "MP_TP_POST", "SVT_POST", "GT_POST", "FIB_G_POST", 
"ant_im", "lat_im", "inf_im", "post_im", "IM_PG_P", "ritm_ecg_p_02", 
"ritm_ecg_p_04", "ritm_ecg_p_06", "ritm_ecg_p_07", "ritm_ecg_p_08", 
"n_r_ecg_p_01", "n_r_ecg_p_02", "n_r_ecg_p_03", "n_r_ecg_p_04", 
"n_r_ecg_p_05", "n_r_ecg_p_06", "n_r_ecg_p_08", "n_r_ecg_p_09", 
"n_r_ecg_p_10", "n_p_ecg_p_01", "n_p_ecg_p_03", "n_p_ecg_p_04", 
"n_p_ecg_p_05", "n_p_ecg_p_06", "n_p_ecg_p_07", "n_p_ecg_p_08", 
"n_p_ecg_p_09", "n_p_ecg_p_10", "n_p_ecg_p_11", "n_p_ecg_p_12", 
"fibr_ter_01", "fibr_ter_02", "fibr_ter_03", "fibr_ter_05", "fibr_ter_06", 
"fibr_ter_07", "fibr_ter_08", "GIPO_K", "K_BLOOD", "GIPER_NA", 
"NA_BLOOD", "ALT_BLOOD", "AST_BLOOD", "L_BLOOD", "ROE", "TIME_B_S", 
"R_AB_1_n", "R_AB_2_n", "R_AB_3_n", "NITR_S", "NA_R_1_n", "NA_R_2_n", 
"NA_R_3_n", "NOT_NA_1_n", "NOT_NA_2_n", "NOT_NA_3_n", "LID_S_n", 
"B_BLOK_S_n", "ANT_CA_S_n", "GEPAR_S_n", "ASP_S_n", "TIKL_S_n", 
"TRENT_S_n")])
yy[1:1700]
head(xx)

# - Use glmnet() function to get solutions path plot;
# because glmnet() fits both LASSO and Ridge regression, use alpha
# argument to specify which penalty to use (alpha = 1 --> LASSO)
fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
cbind(1:103,colnames(xx))

# - Use cv.glment() function to perform k-fold cross validation
# to select the final model; need to set the seed so random
# can be reproduced each time code is run
set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
# - Value of lambda that minimizes MSPE:
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

# - Regression coefficients for selected model
lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: AGE + SEX + STENOK_AN + IBS_POST + nr_03 + np_01 + np_10 + endocr_01 + zab_leg_01 + zab_leg_02 + K_SH_POST + GT_POST + FIB_G_POST + aint_im + lat_im + inf_im + ritm_ecg_p_02 + ritm_ecg_p_07 + n_r_ecg_p_06 + n_r_ecg_p_09 + n_p_ecg_p_03 + n_p_ecg_p_07 + n_p_ecg_p_11 + GIPER_NA + ALT_BLOOD + L_BLOOD + R_AB_3_n + NITR_S + NA_R_1_n + NA_R_2_n + NA_R_3_n + ANT_CA_S_n + GEPAR_S_n + TRENT_S_n

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ADMISSION

yy <- imputed_data_admission[,'REC_IM']
xx <- as.matrix(imputed_data_admission[,c("AGE", "SEX", "INF_ANAM", "STENOK_AN", "FK_STENOK", "IBS_POST", 
"GB", "SIM_GIPERT", "DLIT_AG", "ZSN_A", "nr_11", "nr_01", "nr_02", 
"nr_03", "nr_04", "nr_07", "nr_08", "np_01", "np_04", "np_05", 
"np_07", "np_08", "np_09", "np_10", "endocr_01", "endocr_02", 
"endocr_03", "zab_leg_01", "zab_leg_02", "zab_leg_03", "zab_leg_04", 
"zab_leg_06", "S_AD_ORIT", "D_AD_ORIT", "O_L_POST", "K_SH_POST", 
"MP_TP_POST", "SVT_POST", "GT_POST", "FIB_G_POST", "ant_im", 
"lat_im", "inf_im", "post_im", "IM_PG_P", "ritm_ecg_p_02", 
"ritm_ecg_p_04", "ritm_ecg_p_06", "ritm_ecg_p_07", "ritm_ecg_p_08", 
"n_r_ecg_p_01", "n_r_ecg_p_02", "n_r_ecg_p_03", "n_r_ecg_p_04", 
"n_r_ecg_p_05", "n_r_ecg_p_06", "n_r_ecg_p_08", "n_r_ecg_p_09", 
"n_r_ecg_p_10", "n_p_ecg_p_01", "n_p_ecg_p_03", "n_p_ecg_p_04", 
"n_p_ecg_p_05", "n_p_ecg_p_06", "n_p_ecg_p_07", "n_p_ecg_p_08", 
"n_p_ecg_p_09", "n_p_ecg_p_10", "n_p_ecg_p_11", "n_p_ecg_p_12", 
"fibr_ter_01", "fibr_ter_02", "fibr_ter_03", "fibr_ter_05", "fibr_ter_06", 
"fibr_ter_07", "fibr_ter_08", "GIPO_K", "K_BLOOD", "GIPER_NA", 
"NA_BLOOD", "ALT_BLOOD", "AST_BLOOD", "L_BLOOD", "ROE", "TIME_B_S", 
"NITR_S", "LID_S_n", "B_BLOK_S_n", "ANT_CA_S_n", "GEPAR_S_n", 
"ASP_S_n", "TIKL_S_n", "TRENT_S_n")])
yy[1:1700]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
(main = 'LASSO Regression for General Admission', line=3)
cbind(1:94,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: AGE + SEX + STENOK_AN + IBS_POST + nr_03 + np_01 + np_10 + endocr_01 + zab_leg_01 + zag_leg_02 + K_SH_POST + GT_POST + FIB_G_POST + ant_im + lat_im + ritm_ecg_p_02 + ritm_ecg_p_07 + n_r_ecg_p_06 + n_r_ecg_p_09 + n_p_ecg_p_03 + n_p_ecg_p_11 + GIPER_NA + L_BLOOD + NITR_S + ANT_CA_S_n + GEPAR_S_n + TRENT_S_n  

# ----------------------------------------------------------------------------
# IMPUTED_DATA_STAY

yy <- imputed_data_stay[,'REC_IM']
xx <- as.matrix(imputed_data_stay[,c('R_AB_1_n', 'NA_R_1_n', 'NOT_NA_1_n', 'R_AB_2_n', 'NA_R_2_n', 'NOT_NA_2_n', 'R_AB_3_n', 'NA_R_3_n', 'NOT_NA_3_n')])
yy[1:1700]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
(main = 'LASSO Regression for General Stay', line=3)
cbind(1:9,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: NA_R_1_n + NA_R_2_n + R_AB_3_n + NA_R_3_n

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ECT

yy <- imputed_data_ect[,'REC_IM']
xx <- as.matrix(imputed_data_ect[,c('NOT_NA_KB', 'LID_KB', 'NA_KB', 'S_AD_KBRIG', 'D_AD_KBRIG')])
yy[1:539]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
title(main = 'LASSO Regression for ECT', line=3)
cbind(1:5,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: NOT_NA_KB + LID_KB + NA_KB + D_AD_KBRIG

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ANAMNESIS

yy <- imputed_data_anamnesis[,'REC_IM']
xx <- as.matrix(imputed_data_anamnesis[,c("AGE", "SEX", "INF_ANAM", "STENOK_AN", "FK_STENOK", "IBS_POST", "GB", "DLIT_AG", "ZSN_A", "nr_11", "nr_01", "nr_02", "nr_03", "nr_04", "nr_07", "nr_08", "np_01", "np_04", "np_05", "np_07", "np_08", "np_09", "np_10", "endocr_01", "endocr_02", "endocr_03", "zab_leg_01", "zab_leg_02", "zab_leg_03", "zab_leg_06")])
yy[1:1700]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
title(main = 'LASSO Regression for Anamnesis', line=3)
cbind(1:30,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: AGE + SEX + STENOK_AN + IBS_POST + DLIT_AG + nr_11 + nr_03 + nr_04 + np_01 + np_10 + endocr_01 + zab_leg_01 + zab_leg_02

# ----------------------------------------------------------------------------
# IMPUTED_DATA_HOSPITAL_ADMIT

yy <- imputed_data_hospital_admit[,'REC_IM']
xx <- as.matrix(imputed_data_hospital_admit[,c("ritm_ecg_p_02", "ritm_ecg_p_04", "ritm_ecg_p_06", "ritm_ecg_p_07", 
"ritm_ecg_p_08", "n_r_ecg_p_01", "n_r_ecg_p_02", "n_r_ecg_p_03", 
"n_r_ecg_p_04", "n_r_ecg_p_05", "n_r_ecg_p_06", "n_r_ecg_p_08", 
"n_r_ecg_p_09", "n_r_ecg_p_10", "n_p_ecg_p_01", "n_p_ecg_p_03", 
"n_p_ecg_p_04", "n_p_ecg_p_05", "n_p_ecg_p_06", "n_p_ecg_p_07", 
"n_p_ecg_p_08", "n_p_ecg_p_09", "n_p_ecg_p_10", "n_p_ecg_p_11", 
"n_p_ecg_p_12", "fibr_ter_01", "fibr_ter_02", "fibr_ter_03", 
"fibr_ter_05", "fibr_ter_06", "fibr_ter_07", "fibr_ter_08", "GIPO_K", 
"K_BLOOD", "GIPER_NA", "NA_BLOOD", "ALT_BLOOD", "AST_BLOOD", 
"L_BLOOD", "ROE", "TIME_B_S")])
yy[1:1700]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
title(main = 'LASSO Regression for Hospital Admission', line=3)
cbind(1:41,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: NONE

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ICU_ALL

yy <- imputed_data_ICU_all[,'REC_IM']
xx <- as.matrix(imputed_data_ICU_all[,c("S_AD_ORIT", "D_AD_ORIT", "O_L_POST", "K_SH_POST", "MP_TP_POST", 
"SVT_POST", "GT_POST", "FIB_G_POST", "ant_im", "lat_im", "inf_im", 
"post_im", "IM_PG_P", "NITR_S", "LID_S_n", "B_BLOK_S_n", "ANT_CA_S_n", 
"GEPAR_S_n", "ASP_S_n", "TIKL_S_n", "TRENT_S_n", "R_AB_1_n", 
"R_AB_2_n", "R_AB_3_n", "NA_R_1_n", "NA_R_2_n", "NA_R_3_n", "NOT_NA_1_n", 
"NOT_NA_2_n", "NOT_NA_3_n")])
yy[1:1700]
head(xx)

fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
plot(fit.lasso, label=TRUE, xvar="lambda")
title(main="LASSO Regression for ICU", line=3)
cbind(1:30,colnames(xx))

set.seed(12345)
cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
plot(cv.lasso)
cv.lasso$lambda.min; log(cv.lasso$lambda.min)

lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
lasso.coef
as.vector(lasso.coef)

## Important variables: D_AD_ORIT + K_SH_POST + SVT_POST + GT_POST + lat_im + inf_im + post_im + IM_PG_P + NITR_S + LID_S_n + ANT_CA_S_n + GEPAR_S_n + TRENT_S_n + R_AB_3_n + NA_R_1_n + NA_R_2_n + NOT_NA_2_n

# ----------------------------------------------------------------------------
# IMPUTED_DATA_ICU_ADMIT
# 
# yy <- imputed_data_ICU_admit[,'REC_IM']
# xx <- as.matrix(imputed_data_ICU_admit[,c("S_AD_ORIT", "D_AD_ORIT", "O_L_POST", "K_SH_POST", "MP_TP_POST", "SVT_POST", "GT_POST", "FIB_G_POST", "ant_im", "lat_im", "inf_im", "post_im", "IM_PG_P")])
# yy[1:1700]
# head(xx)
# 
# fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
# plot(fit.lasso, label=TRUE, xvar="lambda")
# cbind(1:13,colnames(xx))
# 
# set.seed(12345)
# cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
# plot(cv.lasso)
# cv.lasso$lambda.min; log(cv.lasso$lambda.min)
# 
# lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
# lasso.coef
# as.vector(lasso.coef)
# 
# ## Important variables: D_AD_ORIT + K_SH_POST + SVT_POST + GT_POST + FIB_G_POST + ant_im + lat_im + inf_im + post_im + IM_PG_P
# 
# # ----------------------------------------------------------------------------
# # IMPUTED_DATA_ICU_STAY
# 
# yy <- imputed_data_ICU_stay[,'REC_IM']
# xx <- as.matrix(imputed_data_ICU_stay[,c("NITR_S", "LID_S_n", "B_BLOK_S_n", "ANT_CA_S_n", "GEPAR_S_n",  "ASP_S_n", "TIKL_S_n", "TRENT_S_n", "R_AB_1_n", "R_AB_2_n", "R_AB_3_n",  "NA_R_1_n", "NA_R_2_n", "NA_R_3_n", "NOT_NA_1_n", "NOT_NA_2_n", "NOT_NA_3_n")])
# yy[1:1700]
# head(xx)
# 
# fit.lasso <- glmnet(xx, yy, alpha=1, standardize=TRUE)
# plot(fit.lasso, label=TRUE, xvar="lambda")
# cbind(1:17,colnames(xx))
# 
# set.seed(12345)
# cv.lasso <- cv.glmnet(xx, yy, alpha=1, standardize=TRUE, nfolds=10)
# plot(cv.lasso)
# cv.lasso$lambda.min; log(cv.lasso$lambda.min)
# 
# lasso.coef <- coef(cv.lasso, s=cv.lasso$lambda.min)
# lasso.coef
# as.vector(lasso.coef)
# 
# ## Important variables: NITR_S + LID_S_n + ANT_CA_S_n + GEPAR_S_n + ASP_S_n + TIKL_S_n + TRENT_S_n + R_AB_3_n + NA_R_1_n + NA_R_2_n + NA_R_3_n + NOT_NA_2_n + NOT_NA_3_n

```

```{r final_model_ADMISSION, echo=FALSE, warning=FALSE}

# ADMISSION
library(caTools)
library(mmpf)

set.seed(123)  # For reproducibility
split <- sample.split(imputed_data_admission$REC_IM, SplitRatio = 0.7)
train_data <- subset(imputed_data_admission, split == TRUE)
test_data <- subset(imputed_data_admission, split == FALSE)

final_fit_admission <- glm(REC_IM ~ lat_im + ANT_CA_S_n + nr_03 + GIPER_NA + L_BLOOD + STENOK_AN + n_p_ecg_p_03 + n_r_ecg_p_09 + K_SH_POST + zab_leg_01 + FIB_G_POST + endocr_01 + NITR_S + GEPAR_S_n + IBS_POST + TRENT_S_n + n_p_ecg_p_11 + AGE + np_01 + n_r_ecg_p_06 + np_10 + ritm_ecg_p_02, data = imputed_data_admission, family = 'binomial')
summary(final_fit_admission)

# --- To get estimates on odds scale, must exponentiate
exp(final_fit_admission$coef)
exp(confint.default(final_fit_admission))

# ----------------------------------------------------------------------
# - Get predicted probabilities of BPD

p.hats <- predict(final_fit_admission,type='response')

# --- Check computation of p.hats for first observation 
head(imputed_data_admission)

# ----- With rounding errors ... 
# xbeta <- 4.0342913 + (-0.0042291*850)   # Manually compute linear predictor 
# p.x <- exp(xbeta)/(1+exp(xbeta)); p.x   # Manually compute P(Y=1|X)
# p.hats[1]                               # Compare to output from predict()  

result <- c(1)  # Initialize the result vector with the first element as 1

for (i in 2:length(final_fit_admission$coef)){
  result <- c(result, final_fit_admission$coef[[i]][1])
}

# ----- Without rounding errors ... 
xbeta <- result %*% final_fit_admission$coef          # Manually compute linear predictor 
p.x <- exp(xbeta)/(1+exp(xbeta)); p.x   # Manually compute P(Y=1|X)
p.hats[1]                               # Compare to output from predict() 

# --- Add predicted probabilities to data set
imputed_data_admission$p.hats <- p.hats

# ----------------------------------------------------------------------
# - Estimate calibration-in-the-large 

mean(imputed_data_admission$p.hats)        # Mean P(Y=1|X)
mean(imputed_data_admission$REC_IM)           # Observed P(Y=1)

# ----------------------------------------------------------------------
# - Create calibration plot  

# --- Summarize predicted probabilities
summary(imputed_data_admission$p.hats)
hist(imputed_data_admission$p.hats)

# --- Compute deciles of predicted probabilities
dec <- quantile(imputed_data_admission$p.hats,            # Variable to be summarized
                probs=seq(0,1,by=0.1), # Vector of percentile values 
                type=3)                # Use same algorithm as SAS
dec 

# --- Create decile group variable 
imputed_data_admission$dec_grp <- cut(imputed_data_admission$p.hats,         # Predicted probabilities (var to group)
                   breaks = dec,       # Cut points (group intervals)
                   include.lowest = T, # Include smallest value 
                   labels = 1:10)      # Labels for groups

# ----- Check that decile groups created correctly 
table(imputed_data_admission$dec_grp)                     # Number of observations in each decile group
prop.table(table(imputed_data_admission$dec_grp))         # Proportion of observations in each decile group

# --- Compute mean predicted probability and event rate by decile group
agg <- aggregate(cbind(REC_IM,p.hats) ~ dec_grp, # Aggregate A,B by C
                 data = imputed_data_admission,                  # From data set
                 FUN = 'mean')                # Using this summary function 
agg

# ----- Check computations for decile group 5
mean(imputed_data_admission$REC_IM[imputed_data_admission$dec_grp == 5])
mean(imputed_data_admission$p.hats[imputed_data_admission$dec_grp == 5])

# --- Create calibration plot 
plot(agg$p.hats,                         # x-coor = mean pred prob in dec group
     agg$REC_IM,                            # y-coor = obs event rate in dec group
     main = 'Calibration Plot',          # Add main title 
     ylab = 'Observed Event Rate',       # Add y-axis label
     xlab = 'Predicted Probabilities',   # Add x-axis label
     pch = 19,                           # Plotting character = solid dot
     col = 'orangered',                  # Color of plotting character 
     cex = 2)                            # Size of plotting character (base = 1)

                                         # Add identity line
abline(a = 0,                            # a = intercept 
       b = 1)                            # b = slope

                                        # Add fitted regression line
cal.fit <- lm(REC_IM ~ p.hats, data = agg) # Fit linear model to plot data 
abline(cal.fit,                         # Using intercept and slope from linear model fit
       lty = 2,                         # Dashed line
       col = 'royalblue',               # Color of plotting line
       lwd = 3)                         # Thickness of plotting line (base = 1)

summary(cal.fit)                        # Compute calibration intercept and slope
confint(cal.fit)                        # Compute  95% confidence intervals

# ----------------------------------------------------------------------
# - Plot density of predicted probabilities by event status

ggplot(imputed_data_admission,                           # Data set to pull variables from 
       aes(p.hats,                    # Variable density to plot 
           fill=as.factor(REC_IM))) +    # Variable to stratify by (has to be a factor)
geom_density(alpha = 0.2) +           # Transparency of plotting colors 
scale_fill_manual(                    # Set plotting colors
  values=c("orangered", "royalblue"), name="Relapse of\nMI",
                       breaks=c("0", "1"),
                       labels=c("No", "Yes")) +
  labs(title='Density of Predictions for Relapse of MI', y='Density', x='Predictions')

library(pROC)  # For ROC curve and AUC

# Make predictions on the test data
predictions <- predict(final_fit_admission, newdata = test_data, type = "response")

# Convert the probabilities into class labels (0 or 1) based on a threshold
threshold <- 0.5
predicted_classes <- ifelse(predictions >= threshold, 1, 0)

# Calculate accuracy
accuracy <- sum(predicted_classes == test_data$REC_IM) / length(test_data$REC_IM)
print(paste("Accuracy:", accuracy))

# Calculate AUC
roc_obj <- roc(test_data$REC_IM, predictions)
auc <- auc(roc_obj)
print(paste("AUC:", auc))

# Generate ROC curve plot
plot(roc_obj, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate")

```

```{r final_model_STAY, echo=FALSE, warning=FALSE}

# STAY

set.seed(123)  # For reproducibility
split <- sample.split(imputed_data_stay$REC_IM, SplitRatio = 0.7)
train_data <- subset(imputed_data_stay, split == TRUE)
test_data <- subset(imputed_data_stay, split == FALSE)


final_fit_stay <- glm(REC_IM ~ R_AB_3_n + NA_R_1_n + NA_R_2_n + NA_R_3_n, data = imputed_data_stay, family = 'binomial')
summary(final_fit_stay)

# --- To get estimates on odds scale, must exponentiate
exp(final_fit_stay$coef)
exp(confint.default(final_fit_stay))

# ----------------------------------------------------------------------
# - Get predicted probabilities of BPD

p.hats <- predict(final_fit_stay,type='response')

# --- Check computation of p.hats for first observation 
head(imputed_data_stay)

# ----- With rounding errors ... 
# xbeta <- 4.0342913 + (-0.0042291*850)   # Manually compute linear predictor 
# p.x <- exp(xbeta)/(1+exp(xbeta)); p.x   # Manually compute P(Y=1|X)
# p.hats[1]                               # Compare to output from predict()  

result <- c(1)  # Initialize the result vector with the first element as 1

for (i in 2:length(final_fit_stay$coef)){
  result <- c(result, final_fit_stay$coef[[i]][1])
}

# ----- Without rounding errors ... 
xbeta <- result %*% final_fit_stay$coef          # Manually compute linear predictor 
p.x <- exp(xbeta)/(1+exp(xbeta)); p.x   # Manually compute P(Y=1|X)
p.hats[1]                               # Compare to output from predict() 

# --- Add predicted probabilities to data set
imputed_data_stay$p.hats <- p.hats

# ----------------------------------------------------------------------
# - Estimate calibration-in-the-large 

mean(imputed_data_stay$p.hats)        # Mean P(Y=1|X)
mean(imputed_data_stay$REC_IM)           # Observed P(Y=1)

# --- Compute deciles of predicted probabilities
dec <- quantile(imputed_data_stay$p.hats,            # Variable to be summarized
                probs = seq(0, 1, by = 0.1),         # Vector of percentile values 
                type = 3,                            # Use same algorithm as SAS
                names = FALSE)                       # Do not include names to avoid duplication
dec <- unique(dec)                                   # Remove duplicate values

# --- Create decile group variable 
imputed_data_stay$dec_grp <- cut(imputed_data_stay$p.hats,         # Predicted probabilities (var to group)
                                breaks = dec,                     # Cut points (group intervals)
                                include.lowest = TRUE,            # Include smallest value 
                                labels = 1:5                    # Labels for groups

# ----- Check that decile groups created correctly 
table(imputed_data_stay$dec_grp)                     # Number of observations in each decile group
prop.table(table(imputed_data_stay$dec_grp))         # Proportion of observations in each decile group

# --- Compute mean predicted probability and event rate by decile group
agg <- aggregate(cbind(REC_IM, p.hats) ~ dec_grp,  # Aggregate A,B by C
                 data = imputed_data_stay,         # From data set
                 FUN = 'mean')                     # Using this summary function 
agg


# ----- Check computations for decile group 5
mean(imputed_data_stay$REC_IM[imputed_data_stay$dec_grp == 5])
mean(imputed_data_stay$p.hats[imputed_data_stay$dec_grp == 5])

# --- Create calibration plot 
plot(agg$p.hats,                         # x-coor = mean pred prob in dec group
     agg$REC_IM,                            # y-coor = obs event rate in dec group
     main = 'Calibration Plot',          # Add main title 
     ylab = 'Observed Event Rate',       # Add y-axis label
     xlab = 'Predicted Probabilities',   # Add x-axis label
     pch = 19,                           # Plotting character = solid dot
     col = 'orangered',                  # Color of plotting character 
     cex = 2)                            # Size of plotting character (base = 1)

                                         # Add identity line
abline(a = 0,                            # a = intercept 
       b = 1)                            # b = slope

                                        # Add fitted regression line
cal.fit <- lm(REC_IM ~ p.hats, data = agg) # Fit linear model to plot data 
abline(cal.fit,                         # Using intercept and slope from linear model fit
       lty = 2,                         # Dashed line
       col = 'royalblue',               # Color of plotting line
       lwd = 3)                         # Thickness of plotting line (base = 1)

summary(cal.fit)                        # Compute calibration intercept and slope
confint(cal.fit)                        # Compute  95% confidence intervals

# ----------------------------------------------------------------------
# - Plot density of predicted probabilities by event status

ggplot(imputed_data_stay,                           # Data set to pull variables from 
       aes(p.hats,                    # Variable density to plot 
           fill=as.factor(REC_IM))) +    # Variable to stratify by (has to be a factor)
geom_density(alpha = 0.2) +           # Transparency of plotting colors 
scale_fill_manual(                    # Set plotting colors
  values=c("orangered", "royalblue"), name="Relapse of\nMI",
                       breaks=c("0", "1"),
                       labels=c("No", "Yes")) +
  labs(title='Density of Predictions for Relapse of MI', y='Density', x='Predictions')

# Make predictions on the test data
predictions <- predict(final_fit_stay, newdata = test_data, type = "response")

# Convert the probabilities into class labels (0 or 1) based on a threshold
threshold <- 0.5
predicted_classes <- ifelse(predictions >= threshold, 1, 0)

# Calculate accuracy
accuracy <- sum(predicted_classes == test_data$REC_IM) / length(test_data$REC_IM)
print(paste("Accuracy:", accuracy))

# Calculate AUC
roc_obj <- roc(test_data$REC_IM, predictions)
auc <- auc(roc_obj)
print(paste("AUC:", auc))

# Generate ROC curve plot
plot(roc_obj, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate")

# Assess the model using the summary
summary(final_fit_stay)

```
