---
title: "Research Plan"
author: "Alayna Binder"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
data <- read.csv('MICD.csv')
```

## Background

The primary goal is to identify risk factors for one of the following MI complications: atrial fibrillation, pulmonary edema, or relapse of the MI.

## Research Questions

1. Which covariates measured at hospital admission are correlated with a complication (i.e., which covariates may be useful for clinicians to monitor when treating MI patients)? Which are associated with an increased risk of complication? Which are associated with a decreased risk of complication?

2. Are covariates measured during the hospital stay correlated with a complication? Do they provide information about the odds of a complication independent of covariates measured at the time of admission (i.e., should clinicians treating MI patients measure these covariates during the hospital stay)?

3. Can these covariates be used to build a model that predicts the odds of a complication?

We will address all three questions in our data analysis and presentation.

## Descriptive Analysis
*Of the cohort being studied, including data visualizations*

## Inferential Analysis
*Including a justification of why the selected statistical methods are appropriate for addressing the selected research questions(s)*

## Discussion and Limitations

* Missing data

