---
title: "Descriptive Analysis"
author: "Alayna Binder, Isabella Shubert, Preeti Nagalamadaka and Olivia Xiao"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidymodels)
library(parsnip)
library(patchwork)
library(plotly)
library(widgetframe)
library(naniar)
data <- read.csv('MICD.csv')
```

```{r descriptive-analysis, echo=FALSE, warning=FALSE}
#hello
superdata <- data

# Creating AGE_GROUP; Recoding SEX
superdata <- superdata %>%
  mutate(AGE_GROUP = case_when(AGE >= 25 & AGE <= 34 ~ '25-34', AGE >= 35 & AGE <= 44 ~ '35-44', AGE >= 45 & AGE <= 54 ~ '45-54', AGE >= 55  & AGE <= 64 ~ '55-64', AGE >= 65 & AGE <= 74 ~ '65-74', AGE >= 75 & AGE <= 84 ~ '75-84', AGE >= 85 ~ '85+')) %>%
  mutate(SEX = case_when(SEX == 0 ~ 'Female', SEX == 1 ~ 'Male')) %>%
  relocate(AGE_GROUP, .after = AGE) 

superdata <- select(superdata, - c(IBS_NASL, KFK_BLOOD, S_AD_KBRIG, D_AD_KBRIG, NOT_NA_KB, LID_KB, NA_KB))

```

```{r testing, echo=FALSE, warning=FALSE}

# Missing Data
# colSums(is.na(superdata))
#figures out which factors are most missing using naniar package
miss_var_summary(data)

#summary of data
#summary(data)

```

```{r tables, echo=FALSE, warning=FALSE}

# write.csv(imputed_data_admission, "./imputed_admission.csv", row.names=FALSE)
# write.csv(imputed_data_stay, "./imputed_stay.csv", row.names=FALSE)
# write.csv(imputed_data_anamnesis, "./imputed_amanesis.csv", row.names=FALSE)
# write.csv(imputed_data_hospital_admit, "./imputed_hospital_admit.csv", row.names=FALSE)
# write.csv(imputed_data_ICU_admit, "./imputed_ICU_admit.csv", row.names=FALSE)
# write.csv(imputed_data_ICU_stay, "./imputed_ICU_stay.csv", row.names=FALSE)

#using data from csv so don't need to do imputation again
imputed_data_admission <- read.csv(./imputed_admission.csv)
imputed_data_stay <- read.csv(./imputed_stay.csv)
imputed_data_amamnesis <- read.csv(./imputed_anamnesis.csv)
imputed_data_hospital_admit <- read.csv(./imputed_hospital_admit.csv)
imputed_data_ICU_admit <- read.csv(./imputed_ICU_admit.csv)
imputed_data_ICU_stay <- read.csv(./imputed_ICU_stay.csv)

```

```{r visualizations, echo=FALSE, warning=FALSE}

#distribution of ages
# barplot(table(data$AGE), col = rainbow(300), main="Distribution of Ages in the Study",
#         xlab="Number of People",
#         ylab="Age")

# Bar Plot for Age Group by Gender
superdata %>%
  drop_na(AGE_GROUP) %>% # Remove NAs
  ggplot(aes(x = AGE_GROUP,
                        fill = SEX)) +
  geom_bar() +
  labs(x = 'Age Group',
       y = 'Count',
       fill = 'Gender',
       title = 'Age Group by Gender')

```
